# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    #- name: espressif
    #  url-base: https://github.com/espressif

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.0.0
      import:
        name-allowlist:
          - hal_espressif

    # maybe this is unneeded
    #- name: esp-idf
    #  remote: espressif
    #  revision: v5.4
